import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./_trpc/Provider";
import Navbar from "./components/sitewide/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <Provider>
      <body className={`${inter.className} antialiased`}>
        <Navbar/>
        {children}
      </body>
      </Provider>
      </html>
    </ClerkProvider>
  );
}
